M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-01-19T19:46:45+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-19T19:46:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X192.595Y-91.79
X192.595Y-97.57
M30
